<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5b682c002fad5',
	'title' => 'Book Purchase Links',
	'fields' => array(
		array(
			'key' => 'field_5b682c1f62940',
			'label' => 'Book Retail Region',
			'name' => 'tfpf_book_retail_region',
			'type' => 'repeater',
			'instructions' => 'Please add a region for your purchase links',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Retail Region',
			'sub_fields' => array(
				array(
					'key' => 'field_5b6830be51b26',
					'label' => 'Region Name',
					'name' => 'tfpf_region_name',
					'type' => 'text',
					'instructions' => 'Please add a name for your purchase region. For example, this could be \'United Kingdom\', \'Europe\' or even \'Wordwide\'.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5b6832cb51b27',
					'label' => 'Book Format',
					'name' => 'tfpf_book_format',
					'type' => 'repeater',
					'instructions' => 'Please add a format type for your book',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add Book Format',
					'sub_fields' => array(
						array(
							'key' => 'field_5b68330751b28',
							'label' => 'Book Format',
							'name' => 'tfpf_book_format_name',
							'type' => 'text',
							'instructions' => 'This can be \'Hardback\', \'Paperback\', \'ebook\' etc.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b68331f51b29',
							'label' => 'Purchase Links',
							'name' => 'tfpf_purchase_links',
							'type' => 'repeater',
							'instructions' => 'Please add your purchase links here',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Purchase Link',
							'sub_fields' => array(
								array(
									'key' => 'field_5b68335351b2a',
									'label' => 'Retailer',
									'name' => 'tfpf_purchase_retailer',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b68336651b2b',
									'label' => 'URL',
									'name' => 'tfpf_purchase_url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'books',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;